version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - '6333:6333'
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334

  backend:
    build: ./backend
    container_name: rag-backend
    env_file: ./backend/.env
    ports:
      - '8000:8000'
    depends_on:
      - qdrant
    volumes:
      - ./widget:/app/widget:ro
      - ./frontend:/app/frontend:ro

  nginx:
    build: ./nginx
    container_name: rag-nginx
    ports:
      - '8081:80'
    depends_on:
      - backend
    volumes:
      - ./widget:/usr/share/nginx/html/widget:ro
      - /etc/letsencrypt/live/test-domain.ru:/etc/nginx/certs:ro

volumes:
  qdrant_storage:
